name: flutter_responsive_admin_panel
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" 
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^0.20.1 
  async: ^2.8.2
  bloc: ^8.0.3
  cached_network_image: ^3.1.0  
  cloud_firestore: ^3.1.12 
  cupertino_icons: ^1.0.4
  data_table_2: ^2.2.2
  email_validator: ^2.0.1
  equatable: ^2.0.3
  file_picker: ^4.6.1
  firebase_auth: ^3.3.9
  firebase_core: ^1.15.1
  firebase_crashlytics: ^2.6.3
  fl_chart: ^0.36.1
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_facebook_auth: ^3.5.6
  flutter_feather_icons: ^2.0.0+1
  flutter_html: ^2.2.1
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.8
  google_fonts: ^2.1.0
  google_sign_in: ^5.2.1 
  html_editor_enhanced: ^2.5.0
  in_app_purchase: ^3.0.1 
  line_icons: ^2.0.1 
  provider: ^6.0.0
  shared_preferences: ^2.0.13 
  shimmer: ^2.0.0
  showcaseview: 1.1.4
  search_page: ^2.0.0+1

  flutter_dropzone: ^3.0.5
  dotted_border: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^2.0.1
 
  
flutter: 
  uses-material-design: true 
  assets:
    - .env
    - .env.example
    - .env.dev
    - .env.production
    - assets/images/
    - assets/icons/